# Desafío con Regex

El siguiente bloque de texto HTML contiene información sobre varios libros disponibles en una tienda. Nuestro objetivo es extraer información clave utilizando **expresiones regulares** y organizarla en una tabla. La información a extraer incluye:

1. **Título del libro**: El texto que se encuentra dentro de las etiquetas `<strong>`.
2. **Autor del libro**: El texto que se encuentra dentro de las etiquetas `<em>`.
3. **Precio**: La cantidad que aparece dentro de las etiquetas `<span>`, precedida por el símbolo de dólar `$`.
4. **Unidades en stock**: El número que aparece después de "unidades en stock" en el texto fuerte `<strong>`.
5. **Correo electrónico**: La dirección de correo que se encuentra dentro de las etiquetas `<a>` con el atributo `href` que comienza con `mailto:`.
6. **Número de teléfono**: El número que se menciona al principio de la frase que contiene la palabra "llama al".
7. **Información de contacto en redes sociales**: Los nombres de usuario que aparecen precedidos por `@`.

A continuación se muestra un ejemplo de cómo podrías escribir un script en Python utilizando **expresiones regulares** para extraer esta información:

In [55]:
import re

# Texto HTML que contiene la información de los libros
texto_html = """
<html>
    <head>
        <title>Catálogo de Libros</title>
    </head>
    <body>
        <h1>Bienvenidos a nuestra tienda de libros</h1>
        <p>Estamos emocionados de presentar una amplia variedad de libros.
        Algunos de nuestros títulos más populares incluyen:</p>
        <div class="producto">
            <p>He estado leyendo un libro fascinante llamado <strong>El Camino del Artista</strong>, de <em>Julia Cameron</em>. 
            Te lo recomiendo mucho, realmente es transformador.
            Por cierto, puedes comprarlo por solo <span>$15.99</span> si te interesa.
            Recuerda que hay <strong>34 unidades en stock</strong>.</p>
            <p>Si deseas más información, contacta a <a href="mailto:julia@example.com">julia@example.com</a> o llama al +34 612 345 678.
            ¡No te olvides de seguir a @juliacameron en redes sociales!</p>
        </div>
        <div class="producto">
            <p>En esta sección, también ofrecemos <strong>Cien años de soledad</strong> de <em>Gabriel García Márquez</em>.
            Es un clásico, aunque el precio de <span>$12.50</span> podría parecer un poco alto.
            Aún así, tenemos <strong>50 unidades en stock</strong>, así que no dudes en preguntar.
            Puedes enviar un correo a <a href="mailto:gabriel@example.com">gabriel@example.com</a> o marcar +57 123 456 7890 para más detalles.</p>
            <p>Además, ¡sigue a @gabrielgarciamarquez en Twitter para actualizaciones!</p>
        </div>
        <div class="producto">
            <p>Si te gustan las historias conmovedoras, deberías leer <strong>El Principito</strong>. Escrito por 
            <em>Antoine de Saint-Exupéry</em>, este libro es ideal para reflexionar sobre la vida. El precio es de solo 
            <span>$10.00</span>. Actualmente, tenemos <strong>120 unidades en stock</strong>, ¡así que no te lo pierdas!</p>
            <p>Para más información, contáctame a <a href="mailto:antoine@example.com">antoine@example.com</a> o al +33 1 23 45 67 89. No te olvides de seguir a @saint_exupery para más contenido interesante.</p>
        </div>
        <div class="producto">
            <p>He escuchado que <strong>La sombra del viento</strong> de <em>Carlos Ruiz Zafón</em> es un gran libro,
            y su precio es de <span>$13.75</span>. Estamos emocionados de tener <strong>78 unidades en stock</strong>.
            La historia es cautivadora, puedes pedir más detalles al <a href="mailto:carlos@example.com">carlos@example.com</a> 
            o al +34 987 654 321.</p>
            <p>No olvides seguir a @carlosruizzafon en Instagram, ¡él comparte mucho contenido interesante!</p>
        </div>
        <div class="producto">
            <p>Finalmente, para aquellos interesados en estrategias, <strong>El arte de la guerra</strong> de <em>Sun Tzu</em> 
            es imprescindible. A solo <span>$9.99</span> y con <strong>25 unidades en stock</strong>, es una gran oportunidad.
            Contacta a <a href="mailto:sun@example.com">sun@example.com</a> o llama al +86 10 1234 5678 para más información.</p>
            <p>Sigue a @suntzu para obtener más consejos estratégicos.</p>
        </div>
        <p>¡Gracias por visitar nuestra tienda de libros! No olvides que también tenemos promociones especiales, así que estate atento. 
        Si necesitas ayuda, estamos aquí para ti. ¡Que tengas un gran día!</p>
    </body>
</html>
"""

In [57]:
# Mostrar DataFrame
titles = re.findall(r"<strong>([^<0-9]+)</strong>",texto_html)
writers = re.findall(r"<em>([^<]+)</em>", texto_html)
prices = re.findall(r"<span>\$(\d+\.\d+)</span>",texto_html)
units_on_stock = re.findall(r"<strong>(\d+)",texto_html)
email_address = re.findall(r"mailto:([a-zA-Z]{1,}@[a-zA-z_]+\.[a-zA-z]+)", texto_html)
telephone_numbers = re.findall(r"\s(\+[\d+\s]+)", texto_html)
social_networks = re.findall(r"\s(@[a-zA-Z0-9_]+)\s", texto_html)

library_data ={
    "Título del libro" : titles,
    "Autor" : writers,
    "Precio" : prices,
    "Unidades en stock" : units_on_stock,
    "Correo electrónico" : email_address,
    "Teléfono" : telephone_numbers,
    "Usuario en redes sociales": social_networks,
}
!pip install pandas
import pandas as pd 
from IPython.display import display
table = pd.DataFrame(data= library_data)
display(table)

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/razieh_ghahartars/.local/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/razieh_ghahartars/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /home/razieh_ghahartars/.local/lib/python3.10/site-packages (from pandas) (2.1.1)
Requirement already satisfied: tzdata>=2022.7 in /home/razieh_ghahartars/.local/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: pytz>=2020.1 in /home/razieh_ghahartars/.local/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

,Título del libro,Autor,Precio,Unidades en stock,Correo electrónico,Teléfono,Usuario en redes sociales
0,El Camino del Artista,Julia Cameron,15.99,34,julia@example.com,+34 612 345 678,@juliacameron
1,Cien años de soledad,Gabriel García Márquez,12.50,50,gabriel@example.com,+57 123 456 7890,@gabrielgarciamarquez
2,El Principito,Antoine de Saint-Exupéry,10.00,120,antoine@example.com,+33 1 23 45 67 89,@saint_exupery
3,La sombra del viento,Carlos Ruiz Zafón,13.75,78,carlos@example.com,+34 987 654 321,@carlosruizzafon
4,El arte de la guerra,Sun Tzu,9.99,25,sun@example.com,+86 10 1234 5678,@suntzu

# Desafío con Regex (Problemas en el Texto)

El siguiente bloque de texto HTML contiene información sobre varios libros disponibles en una tienda. Nuestro objetivo es extraer información clave utilizando **expresiones regulares** y organizarla en una tabla. La información a extraer incluye:

1. **Título del libro**: El texto que se encuentra dentro de las etiquetas `<strong>`.
2. **Autor del libro**: El texto que se encuentra dentro de las etiquetas `<em>`.
3. **Precio**: La cantidad que aparece dentro de las etiquetas `<span>`, precedida por el símbolo de dólar `$`.
4. **Unidades en stock**: El número que aparece después de "unidades en stock" en el texto fuerte `<strong>`.
5. **Correo electrónico**: La dirección de correo que se encuentra dentro de las etiquetas `<a>` con el atributo `href` que comienza con `mailto:`.
6. **Número de teléfono**: El número que se menciona al principio de la frase que contiene la palabra "llama al".
7. **Información de contacto en redes sociales**: Los nombres de usuario que aparecen precedidos por `@`.

A continuación se muestra un ejemplo de cómo podrías escribir un script en Python utilizando **expresiones regulares** para extraer esta información:

In [61]:
import re

# Texto HTML que contiene la información de los libros
texto_html = """
<html>
<head>
<title>Catálogo de Libros</title>
</head>
<body>
<h1>Bienvenidos a nuestra tienda de libros</h1>
<p>Estamos emocionados de presentar una amplia variedad de libros.
Algunos de nuestros títulos más populares incluyen:</p>
<div class="producto">
<p>He estado leyendo un libro fascinante llamado <strong>El
Camino del Artista</strong>, de <em>Julia Cameron</em>. Te lo
recomiendo mucho, realmente es transformador.
Por cierto, puedes comprarlo por solo <span>$15.99</span> si
te interesa.
Recuerda que hay <strong>34 unidades en stock</strong>.</p>
<p>Si deseas más información, contacta a <a
href="mailto:julia@example.com">julia@example.com</a> o llama al +34
612 345 678.
¡No te olvides de seguir a @juliacameron en redes
sociales!</p>
</div>
<div class="producto">
<p>En esta sección, también ofrecemos <strong>Cien años de
soledad</strong> de <em>Gabriel García Márquez</em>.
Es un clásico, aunque el precio de <span>$12.50</span> podría
parecer un poco alto.
Aún así, tenemos <strong>50 unidades en stock</strong>, así
que no dudes en preguntar.
Puedes enviar un correo a <a
href="mailto:gabriel@example.com">gabriel@example.com</a> o marcar +57
123 456 7890 para más detalles.</p>
<p>Además, ¡sigue a @gabrielgarciamarquez en Twitter para
actualizaciones!</p>
</div>
<div class="producto">
<p>Si te gustan las historias conmovedoras, deberías leer
<strong>El Principito</strong>. Escrito por <em>Antoine de Saint-
Exupéry</em>,
este libro es ideal para reflexionar sobre la vida. El precio
es de solo <span>$10.00</span>.
Actualmente, tenemos <strong>120 unidades en stock</strong>,
¡así que no te lo pierdas!</p>
<p>Para más información, contáctame a <a
href="mailto:antoine@example.com">antoine@example.com</a> o al +33 1
23 45 67 89.
No te olvides de seguir a @saint_exupery para más contenido
interesante.</p>
</div>
<div class="producto">
<p>He escuchado que <strong>La sombra del viento</strong> de
<em>Carlos Ruiz Zafón</em> es un gran libro,
y su precio es de <span>$13.75</span>. Estamos emocionados de
tener <strong>78 unidades en stock</strong>.
La historia es cautivadora, puedes pedir más detalles al <a
href="mailto:carlos@example.com">carlos@example.com</a> o al +34 987
654 321.</p>
<p>No olvides seguir a @carlosruizzafon en Instagram, ¡él
comparte mucho contenido interesante!</p>
</div>
<div class="producto">
<p>Finalmente, para aquellos interesados en estrategias,
<strong>El arte de la guerra</strong> de <em>Sun Tzu</em> es
imprescindible.
A solo <span>$9.99</span> y con <strong>25 unidades en
stock</strong>, es una gran oportunidad.
 Contacta a <a
href="mailto:sun@example.com">sun@example.com</a> o llama al +86 10
1234 5678 para más información.</p>
<p>Sigue a @suntzu para obtener más consejos estratégicos.</p>
</div>
<p>¡Gracias por visitar nuestra tienda de libros! No olvides que
también tenemos promociones especiales, así que estate atento. Si
necesitas ayuda, estamos aquí para ti. ¡Que tengas un gran día!</p>
</body>
</html>
"""

In [66]:
# Mostrar DataFrame
texto_html = re.sub(r'\n', " " , texto_html)
titles = re.findall(r"<strong>([^<0-9]+)</strong>",texto_html)
writers = re.findall(r"<em>([^<]+)</em>", texto_html)
prices = re.findall(r"<span>\$(\d+\.\d+)</span>",texto_html)
units_on_stock = re.findall(r"<strong>(\d+)",texto_html)
email_address = re.findall(r"mailto:([a-zA-Z]{1,}@[a-zA-z_]+\.[a-zA-z]+)", texto_html)
telephone_numbers = re.findall(r"\s(\+[\d+\s]+)", texto_html)
social_networks = re.findall(r"\s(@[a-zA-Z_]+)\s", texto_html)

library_data ={
    "Título del libro" : titles,
    "Autor" : writers,
    "Precio" : prices,
    "Unidades en stock" : units_on_stock,
    "Correo electrónico" : email_address,
    "Teléfono" : telephone_numbers,
    "Usuario en redes sociales": social_networks,
}
print(library_data)
table = pd.DataFrame(data= library_data)
display(table)

{'Título del libro': ['El Camino del Artista', 'Cien años de soledad', 'El Principito', 'La sombra del viento', 'El arte de la guerra'], 'Autor': ['Julia Cameron', 'Gabriel García Márquez', 'Antoine de Saint- Exupéry', 'Carlos Ruiz Zafón', 'Sun Tzu'], 'Precio': ['15.99', '12.50', '10.00', '13.75', '9.99'], 'Unidades en stock': ['34', '50', '120', '78', '25'], 'Correo electrónico': ['julia@example.com', 'gabriel@example.com', 'antoine@example.com', 'carlos@example.com', 'sun@example.com'], 'Teléfono': ['+34 612 345 678', '+57 123 456 7890 ', '+33 1 23 45 67 89', '+34 987 654 321', '+86 10 1234 5678 '], 'Usuario en redes sociales': ['@juliacameron', '@gabrielgarciamarquez', '@saint_exupery', '@carlosruizzafon', '@suntzu']}

,Título del libro,Autor,Precio,Unidades en stock,Correo electrónico,Teléfono,Usuario en redes sociales
0,El Camino del Artista,Julia Cameron,15.99,34,julia@example.com,+34 612 345 678,@juliacameron
1,Cien años de soledad,Gabriel García Márquez,12.50,50,gabriel@example.com,+57 123 456 7890,@gabrielgarciamarquez
2,El Principito,Antoine de Saint- Exupéry,10.00,120,antoine@example.com,+33 1 23 45 67 89,@saint_exupery
3,La sombra del viento,Carlos Ruiz Zafón,13.75,78,carlos@example.com,+34 987 654 321,@carlosruizzafon
4,El arte de la guerra,Sun Tzu,9.99,25,sun@example.com,+86 10 1234 5678,@suntzu

# Desafío con Regex

El siguiente bloque de texto HTML contiene información sobre varios dispositivos electrónicos disponibles en una tienda. Nuestro objetivo es extraer información clave utilizando **expresiones regulares** y organizarla en una tabla. La información a extraer incluye:

1. **Nombre del dispositivo**: El texto que se encuentra dentro de las etiquetas `<strong>`, seguido de una etiqueta `<em>`.
2. **Marca del dispositivo**: El texto que se encuentra dentro de las etiquetas `<em>`.
3. **Precio**: La cantidad que aparece dentro de las etiquetas `<span>`, precedida por el símbolo de dólar `$`.
4. **Unidades en stock**: El número que aparece después de "unidades en stock" en el texto fuerte `<strong>`.
5. **Correo electrónico**: La dirección de correo que se encuentra dentro de las etiquetas `<a>` con el atributo `href` que comienza con `mailto:`.
6. **Número de teléfono**: El número que se menciona en el formato internacional, precedido por el símbolo `+`.
7. **Información de contacto en redes sociales**: Los nombres de usuario que aparecen precedidos por `@`.
8. **Código del producto**: El texto que aparece después de "Código del producto:" en el texto fuerte `<strong>`.

Utiliza expresiones regulares en Python para capturar esta información y construir una tabla organizada.

In [99]:
import re

# Texto HTML que contiene la información de los dispositivos
texto_html = """
<html>
<head>
    <title>Catálogo de Dispositivos Electrónicos</title>
</head>
<body>
    <h1>Bienvenidos a nuestra tienda de dispositivos electrónicos</h1>
    <p>Estamos emocionados de presentar una amplia variedad de productos. Algunos de nuestros artículos más populares incluyen:</p>
    
    <div class="producto">
        <p>He estado usando un dispositivo increíble llamado <strong>Smartwatch Pro</strong>, <em>Gadget Corp</em>. 
        Te lo recomiendo mucho, realmente es transformador. Por cierto, puedes comprarlo por solo <span>$199.99</span> si te interesa. 
        Recuerda que hay <strong>50 unidades en stock</strong>. Código del producto: <strong>COD-001</strong>.</p>
        <p>Si deseas más información, contacta a <a href="mailto:support@gadgetcorp.com">support@gadgetcorp.com</a> o llama al +34 612 345 678. 
        ¡No te olvides de seguir a @gadgetcorp en redes sociales!</p>
    </div>

    <div class="producto">
        <p>En esta sección, también ofrecemos <strong>Cámara Ultra HD</strong>, <em>Camera Inc</em>. 
        Es un clásico, aunque el precio de <span>$299.00</span> podría parecer un poco alto. 
        Aún así, tenemos <strong>20 unidades en stock</strong>. Código del producto: <strong>COD-002</strong>.</p>
        <p>Puedes enviar un correo a <a href="mailto:sales@camerainc.com">sales@camerainc.com</a> o marcar +57 123 456 7890 para más detalles.</p>
        <p>Además, ¡sigue a @camera_inc en Twitter para actualizaciones!</p>
    </div>

    <div class="producto">
        <p>Si te gustan los gadgets innovadores, deberías leer sobre <strong>Auriculares Inalámbricos</strong>, <em>SoundWave</em>. 
        Este producto es ideal para disfrutar de la música. El precio es de solo <span>$89.99</span>. 
        Actualmente, tenemos <strong>100 unidades en stock</strong>. Código del producto: <strong>COD-003</strong>.</p>
        <p>Para más información, contáctame a <a href="mailto:info@soundwave.com">info@soundwave.com</a> o al +33 1 23 45 67 89. 
        No te olvides de seguir a @soundwave para más contenido interesante.</p>
    </div>

    <div class="producto">
        <p>He escuchado que <strong>Portátil Ultra Ligero</strong>, <em>TechZone</em> es un gran dispositivo, 
        y su precio es de <span>$799.99</span>. Estamos emocionados de tener <strong>30 unidades en stock</strong>. 
        Código del producto: <strong>COD-004</strong>.</p>
        <p>La historia es cautivadora, puedes pedir más detalles al <a href="mailto:contact@techzone.com">contact@techzone.com</a> o al +34 987 654 321.</p>
        <p>No olvides seguir a @techzone en Instagram, ¡ellos comparten mucho contenido interesante!</p>
    </div>

    <div class="producto">
        <p>Finalmente, para aquellos interesados en videojuegos, <strong>Consola de Juegos Avanzada</strong>, <em>GameSphere</em> es imprescindible. 
        A solo <span>$499.99</span> y con <strong>25 unidades en stock</strong>. Código del producto: <strong>COD-005</strong>.</p>
        <p>Contacta a <a href="mailto:support@gamesphere.com">support@gamesphere.com</a> o llama al +86 10 1234 5678 para más información.</p>
        <p>Sigue a @gamesphere para obtener más consejos estratégicos.</p>
    </div>

    <div class="producto">
        <p>¿Buscas una excelente laptop? <strong>Gamer Laptop X</strong>, <em>UltraTech</em> tiene un rendimiento impresionante. 
        Su precio es de <span>$1,199.00</span> y tenemos <strong>15 unidades en stock</strong>. Código del producto: <strong>COD-006</strong>.</p>
        <p>Escribe a <a href="mailto:info@ultratech.com">info@ultratech.com</a> o llama al +34 912 345 678 para más información.</p>
        <p>También puedes seguir a @ultratech en redes sociales.</p>
    </div>

    <div class="producto">
        <p>Para quienes buscan una pantalla grande, recomendamos el <strong>Monitor 4K</strong>, <em>Visionary</em>. 
        Con un precio de <span>$499.99</span> y <strong>40 unidades en stock</strong>. Código del producto: <strong>COD-007</strong>.</p>
        <p>Contáctanos a través de <a href="mailto:support@visionary.com">support@visionary.com</a> o llama al +34 987 654 321.</p>
        <p>Sigue a @visionary en Twitter para más actualizaciones.</p>
    </div>

    <div class="producto">
        <p>La <strong>Tablet Pro</strong>, <em>TabletMaker</em> es perfecta para el trabajo y el ocio. 
        A solo <span>$349.99</span>, tenemos <strong>60 unidades en stock</strong>. Código del producto: <strong>COD-008</strong>.</p>
        <p>Envía un correo a <a href="mailto:info@tabletmaker.com">info@tabletmaker.com</a> o llama al +34 654 321 987.</p>
        <p>No olvides seguir a @tabletmaker en Instagram.</p>
    </div>

    <div class="producto">
        <p>Para los amantes de la música, los <strong>Altavoces Bluetooth</strong>, <em>SoundBlast</em> son ideales. 
        A un precio de <span>$89.99</span> y <strong>100 unidades en stock</strong>. Código del producto: <strong>COD-009</strong>.</p>
        <p>Puedes contactarnos a <a href="mailto:support@soundblast.com">support@soundblast.com</a> o al +34 321 654 987.</p>
        <p>Sigue a @soundblast en redes sociales.</p>
    </div>

    <div class="producto">
        <p>Por último, los <strong>Relojes Inteligentes</strong>, <em>TimeSmart</em> son perfectos para los entusiastas de la tecnología. 
        Con un precio de <span>$149.99</span> y <strong>75 unidades en stock</strong>. Código del producto: <strong>COD-010</strong>.</p>
        <p>Para consultas, escribe a <a href="mailto:contact@timesmart.com">contact@timesmart.com</a> o llama al +34 765 432 109.</p>
        <p>No olvides seguir a @timesmart para más novedades.</p>
    </div>
    
    <p>¡Gracias por visitar nuestra tienda de dispositivos electrónicos! No olvides que también tenemos promociones especiales, así que estate atento. Si necesitas ayuda, estamos aquí para ti. ¡Que tengas un gran día!</p>
</body>
</html>
"""
nombre_de_dispositivos = re.findall(r'<strong>([^<]+)</strong>,[\s]<em>?',texto_html)
marca_del_dispositivo = re.findall(r'<em>([^<]+)</em>', texto_html)
Precios = re.findall(r'<span>\$([\d+,?\.\d]+)</span>', texto_html)
unidades_en_stock = re.findall(r'<strong>(\d+)', texto_html)
número_de_teléfono = re.findall(r'\+[\d+\s]+', texto_html)
redes_sociales = re.findall(r'\s(@[a-zA-Z_]+)\s', texto_html)
Código_del_producto = re.findall(r'<strong>(\w+-\d+)</strong>' , texto_html)

table_de_dispositivos ={
   "Nombre del dispositivos" : nombre_de_dispositivos, 
   "Nombre del dispositivos count" : len(nombre_de_dispositivos),
   "Marca del dispositivo" : marca_del_dispositivo,
   "Marca del dispositivo count" : len(marca_del_dispositivo),
   "Precio" : Precios, 
   "Precio count" : len(Precios),
   "Unidades en stockUnidades en stock" : unidades_en_stock,
   "unidades_en_stock count" : len(unidades_en_stock),
   "Número de teléfonoNúmero de teléfono" : número_de_teléfono,
   "número_de_teléfono count" : len(número_de_teléfono),
   "número_de_teléfono count" : len(número_de_teléfono),
   "redes sociales" : redes_sociales,
   "redes_sociales count" : len(redes_sociales),
   "Código del producto" : Código_del_producto, 
   "Código_del_producto count" : len(Código_del_producto),
}
#print(table_de_dispositivos)
tabla= pd.DataFrame(table_de_dispositivos)
display(tabla)

,Nombre del dispositivos,Nombre del dispositivos count,Marca del dispositivo,Marca del dispositivo count,Precio,Precio count,Unidades en stockUnidades en stock,unidades_en_stock count,Número de teléfonoNúmero de teléfono,número_de_teléfono count,redes sociales,redes_sociales count,Código del producto,Código_del_producto count
0,Smartwatch Pro,10,Gadget Corp,10,199.99,10,50,10,+34 612 345 678,10,@gadgetcorp,10,COD-001,10
1,Cámara Ultra HD,10,Camera Inc,10,299.00,10,20,10,+57 123 456 7890,10,@camera_inc,10,COD-002,10
2,Auriculares Inalámbricos,10,SoundWave,10,89.99,10,100,10,+33 1 23 45 67 89,10,@soundwave,10,COD-003,10
3,Portátil Ultra Ligero,10,TechZone,10,799.99,10,30,10,+34 987 654 321,10,@techzone,10,COD-004,10
4,Consola de Juegos Avanzada,10,GameSphere,10,499.99,10,25,10,+86 10 1234 5678,10,@gamesphere,10,COD-005,10
5,Gamer Laptop X,10,UltraTech,10,"1,199.00",10,15,10,+34 912 345 678,10,@ultratech,10,COD-006,10
6,Monitor 4K,10,Visionary,10,499.99,10,40,10,+34 987 654 321,10,@visionary,10,COD-007,10
7,Tablet Pro,10,TabletMaker,10,349.99,10,60,10,+34 654 321 987,10,@tabletmaker,10,COD-008,10
8,Altavoces Bluetooth,10,SoundBlast,10,89.99,10,100,10,+34 321 654 987,10,@soundblast,10,COD-009,10
9,Relojes Inteligentes,10,TimeSmart,10,149.99,10,75,10,+34 765 432 109,10,@timesmart,10,COD-010,10

In [100]:
# Mostrar la tabla resultante
tabla

,Nombre del dispositivos,Nombre del dispositivos count,Marca del dispositivo,Marca del dispositivo count,Precio,Precio count,Unidades en stockUnidades en stock,unidades_en_stock count,Número de teléfonoNúmero de teléfono,número_de_teléfono count,redes sociales,redes_sociales count,Código del producto,Código_del_producto count
0,Smartwatch Pro,10,Gadget Corp,10,199.99,10,50,10,+34 612 345 678,10,@gadgetcorp,10,COD-001,10
1,Cámara Ultra HD,10,Camera Inc,10,299.00,10,20,10,+57 123 456 7890,10,@camera_inc,10,COD-002,10
2,Auriculares Inalámbricos,10,SoundWave,10,89.99,10,100,10,+33 1 23 45 67 89,10,@soundwave,10,COD-003,10
3,Portátil Ultra Ligero,10,TechZone,10,799.99,10,30,10,+34 987 654 321,10,@techzone,10,COD-004,10
4,Consola de Juegos Avanzada,10,GameSphere,10,499.99,10,25,10,+86 10 1234 5678,10,@gamesphere,10,COD-005,10
5,Gamer Laptop X,10,UltraTech,10,"1,199.00",10,15,10,+34 912 345 678,10,@ultratech,10,COD-006,10
6,Monitor 4K,10,Visionary,10,499.99,10,40,10,+34 987 654 321,10,@visionary,10,COD-007,10
7,Tablet Pro,10,TabletMaker,10,349.99,10,60,10,+34 654 321 987,10,@tabletmaker,10,COD-008,10
8,Altavoces Bluetooth,10,SoundBlast,10,89.99,10,100,10,+34 321 654 987,10,@soundblast,10,COD-009,10
9,Relojes Inteligentes,10,TimeSmart,10,149.99,10,75,10,+34 765 432 109,10,@timesmart,10,COD-010,10

# Desafío con Regex

El siguiente bloque de texto contiene información sobre varios eventos que se llevarán a cabo en diferentes lugares. Nuestro objetivo es extraer información clave utilizando **expresiones regulares** y organizarla en una tabla. La información a extraer incluye:

1. **Nombre del evento**: El texto que se encuentra entre las etiquetas `<h2>`.
2. **Fecha del evento**: La fecha que se menciona en el formato DD/MM/AAAA dentro de las etiquetas `<date>`.
3. **Hora de inicio**: La hora que se menciona en el formato HH:MM dentro de las etiquetas `<time>`.
4. **Lugar**: El texto que aparece dentro de las etiquetas `<location>`.
5. **Precio**: El monto que aparece precedido por el símbolo de dólar `$` dentro de las etiquetas `<cost>`.
6. **Organizador**: El nombre que se encuentra dentro de las etiquetas `<organizer>`.
7. **Número de contacto**: El número de teléfono en formato internacional precedido por `+` dentro de las etiquetas `<contact>`.
8. **Sitio web**: La URL que se menciona dentro de las etiquetas `<url>`.

Utiliza expresiones regulares en Python para capturar esta información y construir una tabla organizada.

In [110]:
import re

# Texto HTML que contiene la información de los eventos
texto_html = """
<html>
<head>
    <title>Calendario de Eventos</title>
</head>
<body>
    <h1>Eventos Destacados</h1>
    <p>Explora nuestra variedad de eventos programados a lo largo del año.</p>

    <div class="evento">
        <p>Asiste al <h2>Festival de Música</h2>, <em>Sonidos del Mundo</em>. 
        Disfruta de grandes artistas por solo <cost>$50.00</cost>. 
        Hay <strong>100 unidades en stock</strong>. Código del evento: <strong>EVT-001</strong>.</p>
        <p>Contacta a <a href="mailto:info@sonidosdelmundo.com">info@sonidosdelmundo.com</a> o llama al <contact>+34 123 456 789</contact>.</p>
        <p>Sigue a @sonidosdelmundo para más novedades.</p>
        <date>15/05/2024</date>
        <time>18:00</time>
        <location>Auditorio Nacional</location>
        <url>www.sonidosdelmundo.com</url>
    </div>

    <div class="evento">
        <p>No te pierdas la <h2>Carrera de Maratón</h2>, <em>Correr es Vida</em>. 
        Participa por solo <cost>$30.00</cost>. 
        Quedan <strong>200 unidades en stock</strong>. Código del evento: <strong>EVT-002</strong>.</p>
        <p>Puedes enviar un correo a <a href="mailto:contacto@correresvida.com">contacto@correresvida.com</a> o llamar al <contact>+34 987 654 321</contact>.</p>
        <p>Sigue a @correresvida para actualizaciones.</p>
        <date>20/06/2024</date>
        <time>09:00</time>
        <location>Parque Central</location>
        <url>www.correresvida.com</url>
    </div>

    <div class="evento">
        <p>Ven al <h2>Simposio de Tecnología</h2>, <em>Innovadores</em>. 
        A un costo de <cost>$100.00</cost>. 
        Disponibles <strong>150 unidades en stock</strong>. Código del evento: <strong>EVT-003</strong>.</p>
        <p>Para más información, contacta a <a href="mailto:info@innovadores.com">info@innovadores.com</a> o al <contact>+34 321 654 987</contact>.</p>
        <p>Sigue a @innovadores en redes sociales.</p>
        <date>10/07/2024</date>
        <time>10:00</time>
        <location>Centro de Convenciones</location>
        <url>www.innovadores.com</url>
    </div>

    <div class="evento">
        <p>Participa en la <h2>Exposición de Arte</h2>, <em>Artistas Unidos</em>. 
        El precio es de <cost>$25.00</cost>. 
        Tenemos <strong>50 unidades en stock</strong>. Código del evento: <strong>EVT-004</strong>.</p>
        <p>Contacta a <a href="mailto:info@artistasunidos.com">info@artistasunidos.com</a> o llama al <contact>+34 987 654 321</contact>.</p>
        <p>No olvides seguir a @artistasunidos en Instagram.</p>
        <date>25/08/2024</date>
        <time>11:00</time>
        <location>Galería de Arte Moderno</location>
        <url>www.artistasunidos.com</url>
    </div>

    <div class="evento">
        <p>Únete al <h2>Congreso de Salud</h2>, <em>Salud y Bienestar</em>. 
        A solo <cost>$75.00</cost>. 
        Tenemos <strong>80 unidades en stock</strong>. Código del evento: <strong>EVT-005</strong>.</p>
        <p>Puedes escribir a <a href="mailto:contacto@saludybienestar.com">contacto@saludybienestar.com</a> o al <contact>+34 654 321 987</contact>.</p>
        <p>Sigue a @saludybienestar para más información.</p>
        <date>30/09/2024</date>
        <time>15:00</time>
        <location>Centro de Salud y Bienestar</location>
        <url>www.saludybienestar.com</url>
    </div>

    <div class="evento">
        <p>Disfruta de la <h2>Feria del Libro</h2>, <em>Lector en Acción</em>. 
        A un costo de <cost>$10.00</cost>. 
        Quedan <strong>500 unidades en stock</strong>. Código del evento: <strong>EVT-006</strong>.</p>
        <p>Escribe a <a href="mailto:info@lectoraccion.com">info@lectoraccion.com</a> o llama al <contact>+34 654 321 000</contact>.</p>
        <p>Más información en @lectoraccion.</p>
        <date>05/10/2024</date>
        <time>10:00</time>
        <location>Biblioteca Municipal</location>
        <url>www.lectoraccion.com</url>
    </div>

    <div class="evento">
        <p>Asiste a la <h2>Conferencia sobre Innovación</h2>, <em>Futuro Brillante</em>. 
        Participa por <cost>$60.00</cost>. 
        Disponibles <strong>300 unidades en stock</strong>. Código del evento: <strong>EVT-007</strong>.</p>
        <p>Puedes contactarnos a <a href="mailto:info@futurobrillante.com">info@futurobrillante.com</a> o al <contact>+34 987 123 456</contact>.</p>
        <p>Sigue a @futurobrillante para actualizaciones.</p>
        <date>15/11/2024</date>
        <time>14:00</time>
        <location>Auditorio Principal</location>
        <url>www.futurobrillante.com</url>
    </div>

    <div class="evento">
        <p>Únete al <h2>Seminario de Marketing Digital</h2>, <em>Marketing al Día</em>. 
        A solo <cost>$45.00</cost>. 
        Hay <strong>250 unidades en stock</strong>. Código del evento: <strong>EVT-008</strong>.</p>
        <p>Contacta a <a href="mailto:info@marketingaldia.com">info@marketingaldia.com</a> o llama al <contact>+34 321 987 654</contact>.</p>
        <p>No olvides seguir a @marketingaldia en redes sociales.</p>
        <date>12/12/2024</date>
        <time>16:00</time>
        <location>Centro de Formación</location>
        <url>www.marketingaldia.com</url>
    </div>

    <div class="evento">
        <p>No te pierdas la <h2>Encuentro de Fotografía</h2>, <em>Captura el Momento</em>. 
        A un costo de <cost>$35.00</cost>. 
        Quedan <strong>150 unidades en stock</strong>. Código del evento: <strong>EVT-009</strong>.</p>
        <p>Puedes contactarnos a <a href="mailto:info@capturaelmomento.com">info@capturaelmomento.com</a> o al <contact>+34 999 654 321</contact>.</p>
        <p>Sigue a @capturaelmomento para más información.</p>
        <date>20/01/2025</date>
        <time>10:30</time>
        <location>Estudio Fotográfico</location>
        <url>www.capturaelmomento.com</url>
    </div>

    <div class="evento">
        <p>Participa en la <h2>Convención de Videojuegos</h2>, <em>Gamer Fest</em>. 
        El precio es de <cost>$80.00</cost>. 
        Hay <strong>200 unidades en stock</strong>. Código del evento: <strong>EVT-010</strong>.</p>
        <p>Escribe a <a href="mailto:info@gamerfest.com">info@gamerfest.com</a> o llama al <contact>+34 888 888 888</contact>.</p>
        <p>No olvides seguir a @gamerfest en redes sociales.</p>
        <date>01/02/2025</date>
        <time>11:00</time>
        <location>Centro de Exposiciones</location>
        <url>www.gamerfest.com</url>
    </div>
</body>
</html>
"""
nombre_del_evento = re.findall(r"<h2>([^<]+)</h2>" , texto_html)
print("Nombre_del_evento", Nombre_del_evento)
fecha_del_evento = re.findall(r"<date>([^<]+)</date>" , texto_html)
print("Fecha_del_evento", Fecha_del_evento)
hora_de_inicio =re.findall(r"<time>([^<]+)</time>" , texto_html)
print("Hora_de_inicio", Hora_de_inicio)
lugar = re.findall(r"<location>([^<]+)</location>" , texto_html)
print("Lugar", Lugar)
precio = re.findall(r"<cost>([^<]+)</cost>" , texto_html)
print("Precio", Precio)
organizador = re.findall(r"<em>([^<]+)</em>" , texto_html)
print("Organizador", Organizador)
número_de_contacto = re.findall(r"\+[\d+\s]+" , texto_html)
print("Número_de_contacto", Número_de_contacto)
sitio_web = re.findall(r"<url>([^<]+)</url>" , texto_html)
print("Sitio_web", Sitio_web)

dictionario_del_evento ={
    "Nombre del evento" : nombre_del_evento,
    "Fecha del evento" : fecha_del_evento,
    "Hora de inicio" : hora_de_inicio, 
    "Lugar" : lugar, 
    "Precio" : precio,
    "Organizador" : organizador,
    "Numero de contacto	": número_de_contacto,
    "Sitio Web": sitio_web ,    
}

table = pd.DataFrame(dictionario_del_evento)
display(table)

Nombre_del_evento ['Festival de Música', 'Carrera de Maratón', 'Simposio de Tecnología', 'Exposición de Arte', 'Congreso de Salud', 'Feria del Libro', 'Conferencia sobre Innovación', 'Seminario de Marketing Digital', 'Encuentro de Fotografía', 'Convención de Videojuegos']
Fecha_del_evento ['15/05/2024', '20/06/2024', '10/07/2024', '25/08/2024', '30/09/2024', '05/10/2024', '15/11/2024', '12/12/2024', '20/01/2025', '01/02/2025']
Hora_de_inicio ['18:00', '09:00', '10:00', '11:00', '15:00', '10:00', '14:00', '16:00', '10:30', '11:00']
Lugar ['Auditorio Nacional', 'Parque Central', 'Centro de Convenciones', 'Galería de Arte Moderno', 'Centro de Salud y Bienestar', 'Biblioteca Municipal', 'Auditorio Principal', 'Centro de Formación', 'Estudio Fotográfico', 'Centro de Exposiciones']
Precio ['$50.00', '$30.00', '$100.00', '$25.00', '$75.00', '$10.00', '$60.00', '$45.00', '$35.00', '$80.00']
Organizador ['Sonidos del Mundo', 'Correr es Vida', 'Innovadores', 'Artistas Unidos', 'Salud y Bienestar', 'Lector en Acción', 'Futuro Brillante', 'Marketing al Día', 'Captura el Momento', 'Gamer Fest']
Número_de_contacto ['+34 123 456 789', '+34 987 654 321', '+34 321 654 987', '+34 987 654 321', '+34 654 321 987', '+34 654 321 000', '+34 987 123 456', '+34 321 987 654', '+34 999 654 321', '+34 888 888 888']
Sitio_web ['www.sonidosdelmundo.com', 'www.correresvida.com', 'www.innovadores.com', 'www.artistasunidos.com', 'www.saludybienestar.com', 'www.lectoraccion.com', 'www.futurobrillante.com', 'www.marketingaldia.com', 'www.capturaelmomento.com', 'www.gamerfest.com']

,Nombre del evento,Fecha del evento,Hora de inicio,Lugar,Precio,Organizador,Numero de contacto\t,Sitio Web
0,Festival de Música,15/05/2024,18:00,Auditorio Nacional,$50.00,Sonidos del Mundo,+34 123 456 789,www.sonidosdelmundo.com
1,Carrera de Maratón,20/06/2024,09:00,Parque Central,$30.00,Correr es Vida,+34 987 654 321,www.correresvida.com
2,Simposio de Tecnología,10/07/2024,10:00,Centro de Convenciones,$100.00,Innovadores,+34 321 654 987,www.innovadores.com
3,Exposición de Arte,25/08/2024,11:00,Galería de Arte Moderno,$25.00,Artistas Unidos,+34 987 654 321,www.artistasunidos.com
4,Congreso de Salud,30/09/2024,15:00,Centro de Salud y Bienestar,$75.00,Salud y Bienestar,+34 654 321 987,www.saludybienestar.com
5,Feria del Libro,05/10/2024,10:00,Biblioteca Municipal,$10.00,Lector en Acción,+34 654 321 000,www.lectoraccion.com
6,Conferencia sobre Innovación,15/11/2024,14:00,Auditorio Principal,$60.00,Futuro Brillante,+34 987 123 456,www.futurobrillante.com
7,Seminario de Marketing Digital,12/12/2024,16:00,Centro de Formación,$45.00,Marketing al Día,+34 321 987 654,www.marketingaldia.com
8,Encuentro de Fotografía,20/01/2025,10:30,Estudio Fotográfico,$35.00,Captura el Momento,+34 999 654 321,www.capturaelmomento.com
9,Convención de Videojuegos,01/02/2025,11:00,Centro de Exposiciones,$80.00,Gamer Fest,+34 888 888 888,www.gamerfest.com

In [51]:
# Mostrar la tabla resultante
tabla

,Nombre del evento,Fecha del evento,Hora de inicio,Lugar,Precio,Organizador,Numero de contacto,Sitio Web
0,Festival de Música,15/05/2024,18:00,Auditorio Nacional,50.00,Sonidos del Mundo,+34 123 456 789,www.sonidosdelmundo.com
1,Carrera de Maratón,20/06/2024,09:00,Parque Central,30.00,Correr es Vida,+34 987 654 321,www.correresvida.com
2,Simposio de Tecnología,10/07/2024,10:00,Centro de Convenciones,100.00,Innovadores,+34 321 654 987,www.innovadores.com
3,Exposición de Arte,25/08/2024,11:00,Galería de Arte Moderno,25.00,Artistas Unidos,+34 987 654 321,www.artistasunidos.com
4,Congreso de Salud,30/09/2024,15:00,Centro de Salud y Bienestar,75.00,Salud y Bienestar,+34 654 321 987,www.saludybienestar.com
5,Feria del Libro,05/10/2024,10:00,Biblioteca Municipal,10.00,Lector en Acción,+34 654 321 000,www.lectoraccion.com
6,Conferencia sobre Innovación,15/11/2024,14:00,Auditorio Principal,60.00,Futuro Brillante,+34 987 123 456,www.futurobrillante.com
7,Seminario de Marketing Digital,12/12/2024,16:00,Centro de Formación,45.00,Marketing al Día,+34 321 987 654,www.marketingaldia.com
8,Encuentro de Fotografía,20/01/2025,10:30,Estudio Fotográfico,35.00,Captura el Momento,+34 999 654 321,www.capturaelmomento.com
9,Convención de Videojuegos,01/02/2025,11:00,Centro de Exposiciones,80.00,Gamer Fest,+34 888 888 888,www.gamerfest.com